### ISSUE TITLE
Documentação do repositório

### ISSUE THREAD

**Issue by lguima** [Minhacps/votacidade#41]
## **Critérios de aceite**
- [Criar template para Issues](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates)
  - Estória
    - Critério de aceite
    - Labels
  - Atividade
  - Bug
    - Type
      - Accessibility
      - Automation
      - Crash
      - Functional
      - Layout
      - Performance
      - Security
      - Typing
      - Usability
      - Other (Please specific)
    - Steps to Reproduce
    - Actual Result
    - Expected Result
    - Evidences
    - Root Cause
  - Aplicar aos repositórios `votacidade-app` e `votacidade-site` apontado para `votacidade`

- [Criar template para Pull Requests](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates)
  - Verificar a ciência com o Guia de Contribuição
  - Verificar a ciência com o Código de Conduta
  - Verificar a existência de outra Pull Request semelhante para evitar duplicata
  - Vincular issues existentes ou considerar criar uma nova
  - Aplicar aos repositórios `votacidade-app` e `votacidade-site`

- Revisar o README para mover o Código de Conduta para o Guia de Contribuição

## **Tarefas**
- [x] Criar template para Issues #48 
- [x] Criar template para Pull Requests #50
- [x] Revisar o README para mover o Código de Conduta para o Guia de Contribuição #51
